export const fileSortType = {
  FileSize: 0,
  Duration: 1,
  ImportTime: 2,
  FileType: 3,
  Random: 4,
  Width: 5,
  Height: 6,
  Ratio: 7,
  NumberOfPixels: 8,
  NumberOfTags: 9,
  NumberOfMediaViews: 10,
  TotalMediaViewtime: 11,
  ApproximateBitrate: 12,
  HasAudio: 13,
  ModifiedTime: 14,
  Framerate: 15,
  NumberOfFrames: 16,
  LastViewedTime: 18,
  ArchiveTimestamp: 19,
  HashHex: 20,
} as const;
