version: '3.8'
volumes:
  tor-config:
    driver: local
  hybooru-pg-data:
    driver: local
  hydrus-server:
    driver: local
  hydrus-client:
    driver: local
  ipfs-data:
    driver: local
  hydownloader-data:
    driver: local
services:
  hydrusclient:
    image: ghcr.io/hydrusnetwork/hydrus:latest
    container_name: hydrusclient
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - hydrus-client:/opt/hydrus/db
    tmpfs:
      - /tmp #optional for SPEEEEEEEEEEEEEEEEEEEEEEEEED and less disk access
    ports:
      - 5800:5800   #noVNC
      - 5900:5900   #VNC
      - 45868:45868 #Booru
      - 47869:45869 #API

#  hydrusserver:
#    image: ghcr.io/hydrusnetwork/hydrus:server
#    container_name: hydrusserver
#    restart: unless-stopped
#    volumes:
#      - hydrus-server:/opt/hydrus/db
#
#  hydrusclient-ipfs:
#    image: ipfs/go-ipfs
#    container_name: hydrusclient-ipfs
#    restart: unless-stopped
#    volumes:
#      - ipfs-data:/data/ipfs
#      - hydrus-clients:/data/db:ro
#    ports:
#      - 4001:4001 # READ
#      - 5001:5001 # THE
#      - 8080:8080 # IPFS
#      - 8081:8081 # DOCS
#
#  hydrus-web:
#    image: floogulinc/hydrus-web
#    container_name: hydrus-web
#    restart: always
#    ports:
#      - 8080:80 # READ

#  hybooru-pg:
#    image: healthcheck/postgres
#    container_name: hybooru-pg
#    environment:
#      - POSTGRES_USER=hybooru
#      - POSTGRES_PASSWORD=hybooru
#      - POSTGRES_DB=hybooru
#    volumes:
#      - hybooru-pg-data:/var/lib/postgresql/data
#    restart: unless-stopped
